/*******************************************************************************
 * * Copyright (c) 2014, UIA
 * * All rights reserved.
 * * Redistribution and use in source and binary forms, with or without
 * * modification, are permitted provided that the following conditions are met:
 * *
 * *     * Redistributions of source code must retain the above copyright
 * *       notice, this list of conditions and the following disclaimer.
 * *     * Redistributions in binary form must reproduce the above copyright
 * *       notice, this list of conditions and the following disclaimer in the
 * *       documentation and/or other materials provided with the distribution.
 * *     * Neither the name of the {company name} nor the
 * *       names of its contributors may be used to endorse or promote products
 * *       derived from this software without specific prior written permission.
 * *
 * * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY
 * * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * * DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 * * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 05:31:46 PM CST 
//


package uia.message.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BitBlockListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BitBlockListType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://message.uia/model/xml}BitBlockType">
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="countBlock" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="countFactor" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="countFactorOp" type="{http://www.w3.org/2001/XMLSchema}string" default="/" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BitBlockListType")
public class BitBlockListType
    extends BitBlockType
{

    @XmlAttribute(name = "count")
    protected Integer count;
    @XmlAttribute(name = "countBlock")
    protected String countBlock;
    @XmlAttribute(name = "countFactor")
    protected Integer countFactor;
    @XmlAttribute(name = "countFactorOp")
    protected String countFactorOp;

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCount() {
        if (count == null) {
            return  1;
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the countBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountBlock() {
        return countBlock;
    }

    /**
     * Sets the value of the countBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountBlock(String value) {
        this.countBlock = value;
    }

    /**
     * Gets the value of the countFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCountFactor() {
        if (countFactor == null) {
            return  1;
        } else {
            return countFactor;
        }
    }

    /**
     * Sets the value of the countFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCountFactor(Integer value) {
        this.countFactor = value;
    }

    /**
     * Gets the value of the countFactorOp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountFactorOp() {
        if (countFactorOp == null) {
            return "/";
        } else {
            return countFactorOp;
        }
    }

    /**
     * Sets the value of the countFactorOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountFactorOp(String value) {
        this.countFactorOp = value;
    }

}
