/*******************************************************************************
 * Copyright 2017 UIA
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 05:56:42 PM CST
//
package uia.message.model.xml;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;

public class BitBlockType extends BlockBaseType {

    @Element(name = "CodecPropSet", required = false)
    protected CodecPropSetType codecPropSet;

    @Attribute(required = false)
    protected String dataType;

    @Attribute(required = false)
    protected String sizeUnit;

    @Attribute(required = false)
    protected Integer size;

    @Attribute(required = false)
    protected String sizeBlock;

    @Attribute(required = false)
    protected String sizeFx;

    @Attribute(required = false)
    protected Boolean readonly;

    public CodecPropSetType getCodecPropSet() {
        return this.codecPropSet;
    }

    public void setCodecPropSet(CodecPropSetType value) {
        this.codecPropSet = value;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String value) {
        this.dataType = value;
    }

    public String getSizeUnit() {
        if (this.sizeUnit == null) {
            return "byte";
        }
        else {
            return this.sizeUnit;
        }
    }

    public void setSizeUnit(String value) {
        this.sizeUnit = value;
    }

    public int getSize() {
        if (this.size == null) {
            return 1;
        }
        else {
            return this.size;
        }
    }

    public void setSize(Integer value) {
        this.size = value;
    }

    public String getSizeBlock() {
        return this.sizeBlock;
    }

    public void setSizeBlock(String value) {
        this.sizeBlock = value;
    }

    public String getSizeFx() {
        return this.sizeFx;
    }

    public void setSizeFx(String value) {
        this.sizeFx = value;
    }

    public boolean isReadonly() {
        if (this.readonly == null) {
            return false;
        }
        else {
            return this.readonly;
        }
    }

    public void setReadonly(Boolean value) {
        this.readonly = value;
    }

}
