/*******************************************************************************
 * Copyright 2017 UIA
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 05:56:42 PM CST
//
package uia.message.model.xml;

import org.simpleframework.xml.Attribute;

public abstract class BlockBaseType {

    @Attribute
    protected String name;

    @Attribute(required = false)
    protected String desc;

    @Attribute(required = false)
    protected String optionBlock;

    @Attribute(required = false)
    protected String optionValue;

    @Attribute(required = false)
    protected Boolean optionEq;

    @Attribute(required = false)
    protected String optionFx;

    public String getName() {
        return this.name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getDesc() {
        if (this.desc == null) {
            return "no description";
        }
        else {
            return this.desc;
        }
    }

    public void setDesc(String value) {
        this.desc = value;
    }

    public String getOptionBlock() {
        return this.optionBlock;
    }

    public void setOptionBlock(String value) {
        this.optionBlock = value;
    }

    public String getOptionValue() {
        return this.optionValue;
    }

    public void setOptionValue(String value) {
        this.optionValue = value;
    }

    public boolean isOptionEq() {
        if (this.optionEq == null) {
            return true;
        }
        else {
            return this.optionEq;
        }
    }

    public void setOptionEq(Boolean value) {
        this.optionEq = value;
    }

    public String getOptionFx() {
        if (this.optionFx == null) {
            return "EQ";
        }
        else {
            return this.optionFx;
        }
    }

    public void setOptionFx(String value) {
        this.optionFx = value;
    }
}
