/*******************************************************************************
 * Copyright 2017 UIA
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 05:56:42 PM CST
//
package uia.message.model.xml;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Root(name = "DataEx")
public class DataExType {

    @Element(name = "BlockSpace", required = false)
    protected BlockSpaceType blockSpace;

    @Element(name = "MessageSpace")
    protected MessageSpaceType messageSpace;

    @Element(name = "BlockCodecSpace", required = false)
    protected BlockCodecSpaceType blockCodecSpace;

    @Element(name = "FxSpace", required = false)
    protected FxSpaceType fxSpace;

    public BlockSpaceType getBlockSpace() {
        return this.blockSpace;
    }

    public void setBlockSpace(BlockSpaceType value) {
        this.blockSpace = value;
    }

    public MessageSpaceType getMessageSpace() {
        return this.messageSpace;
    }

    public void setMessageSpace(MessageSpaceType value) {
        this.messageSpace = value;
    }

    public BlockCodecSpaceType getBlockCodecSpace() {
        return this.blockCodecSpace;
    }

    public void setBlockCodecSpace(BlockCodecSpaceType value) {
        this.blockCodecSpace = value;
    }

    public FxSpaceType getFxSpace() {
        return this.fxSpace;
    }

    public void setFxSpace(FxSpaceType value) {
        this.fxSpace = value;
    }

}
