//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 08:34:42 \u4e0a\u5348 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://message.uia/model/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uia.message.model.xml;
